FFA-g=9.8066f
DAMAGE_COOLDOWN=0.75f
CAM_WEIGHT=5f
RECOIL_DRAG=5000f
PLAYER_MAX_SPEED=350
PLAYER_WEIGHT=80
PLAYER_FRICTION=12f
FRICTION_BLOCK_MARGIN=0.1f
REVERSE_ANIMATION_ANGLE_DELTA=45f
DEFAULT_PLAYER_FRAME_DUR=0.1f
